[package]
name = "irospace"
version = "0.0.1"
authors = ["prozolic <42107886+prozolic@users.noreply.github.com>"]
edition = "2018"
description = "color space and conversion method"
license = "MIT"
keywords = ["color"]
tags = ["color"]

[dependencies]
